### Business creation (basic data)

POST http://localhost:3000/api/admin/createBusiness HTTP/1.1
Content-Type: application/json

{
    "name": "Casa Pepe",
    "cif": "123456789",
    "address": "C/ Mercurio, 23",
    "email": "peponi@aol.com",
    "phone": "620679945",
    "city": "Lelystad",
    "activity": "Food and Beverage",
    "title": null,
    "summary":null,
    "images":null,
    "texts":null,
    "votes": 0,
    "votesPositive": 0,
    "score": 0,
    "reviews": null
}

### Update 649ab5f377ce0f8437fb55e4 Jeremy Lijtelin

PUT http://localhost:3000/api/admin/editBusiness?id=649ab5f377ce0f8437fb55e4 HTTP/1.1
Content-Type: application/json

{
    "name":"Jermy Lij",
    "cif":69,
    "address":"15 Bunker Hill Parkway",
    "email":"tiamo@aol.com",
    "phone":"2251654720",
    "city":"Lelystad",
    "activity":"Education and Training",
    "title":"Yoveo",
    "summary":"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    "images":"http://dummyimage.com/184x100.png/cc0000/ffffff",
    "texts":"Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "votes":7667,
    "votesPositive":76,
    "score":11,
    "reviews":""
}

### Delete a business by id

DELETE http://localhost:3000/api/admin/deleteBusiness?id=649af9bf518f2313f1f3ce7a HTTP/1.1

### TODO TESTING GET businesses that match a city and an activity ordered by score

GET http://localhost:3000/api/getBusiness/byCity&Activity?city=Lelystad&activity=Education%20and%20Training&order=score HTTP/1.1
###
GET http://localhost:3000/api/getBusiness HTTP/1.1