GET http://localhost:3000/api/tracks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE


###

GET http://localhost:3000/api/tracks/63fba226c391fd40d29c4dd7

###

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MWQ1ODU0YWJlNWU2ODM2ZTU5ZGEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjkyMjQsImV4cCI6MTY3ODEzNjQyNH0.aq8mBYiwj20lPXqkxaIKP_hazvGd1HnRzo_hiVRi9Tc

{
    "dato": "basura",
    "name": "Ric",
    "album": "Album",
    "cover": "http://tttt.com",
    "artist": {
        "name": "Ric",
        "nickname": "rsurname",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###

PUT http://localhost:3000/api/tracks/63fba226c391fd40d29c4dd7 HTTP/1.1
Content-Type: application/json

{
    "name": "Ric4",
    "album": "Album2",
    "cover": "http://t2.com",
    "artist": {
        "name": "Ric4",
        "nickname": "surname2",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###

DELETE http://localhost:3000/api/tracks/63fba226c391fd40d29c4dd7

###

GET http://localhost:3000/api/storage

###

POST http://localhost:3000/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./img.jpg
--Boundry--

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "Menganito",
    "age": 20,
    "email": "admin8@test.com",
    "password": "HolaMundo.01",
    "role": "admin"
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test12@test.com",
    "password": "HolaMundo.01"
}

###