### 

POST http://localhost:3000/api/admin/uploadBusiness HTTP/1.1
Content-Type: application/json

{
    "name": "Casa Pepe",
    "CIF": "123456789",
    "address": "C/ Mercurio, 23",
    "email": "peponi@aol.com",
    "phone": "620679945",
    "city": null,
    "activity": null,
    "title": null,
    "summary":null,
    "images":null,
    "texts":null,
    "votes":null,
    "votesPositives": null,
    "reviews": null
}

### 

GET http://localhost:3000/hello?person=James HTTP/1.1
