### Edit user

PATCH http://localhost:3000/api/registeredUser/editUser?id=64a0698288f4a8fbeb821960 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGEwNjk4Mjg4ZjRhOGZiZWI4MjE5NjEiLCJuYW1lIjoiUmljYXJkbyBQYWxhY2lvcyIsImVtYWlsIjoicnBhbGFjaW9zQHUtdGFkLmNvbSIsImlhdCI6MTY4ODI5MDEyNywiZXhwIjoxNjg4MjkzNzI3fQ.g_BDlNoWXTPJHc4Ruhrbx9X3nV-fpTBAQKKX4gtnYf0

{
    "name":"Ric Palacios",
    "city":"Barcelona"
}

### Delete user

DELETE http://localhost:3000/api/registeredUser/deleteUser?id=649f04c7ac6aba0c50d4dd29 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGEwMDRlOTE2ZjhiZWVmY2NmZGQ3MjYiLCJuYW1lIjoiUmljIFBhbGFjaW9zIiwiZW1haWwiOiJycGFsYWNpb3NAdS10YWQuY29tIiwiaWF0IjoxNjg4MjEwNjU0LCJleHAiOjE2ODgyMTQyNTR9.YnL1EE8yIXGjF6Y3hxgQSnkKC5K5uVGR2l2te8mZVIw

### Vote on a business, with optional review text

PATCH http://localhost:3000/api/registeredUser/voteBusiness?id=64a06a1c88f4a8fbeb821969 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGEwNjk4Mjg4ZjRhOGZiZWI4MjE5NjEiLCJuYW1lIjoiUmljYXJkbyBQYWxhY2lvcyIsImVtYWlsIjoicnBhbGFjaW9zQHUtdGFkLmNvbSIsImlhdCI6MTY4ODIzNDM3NCwiZXhwIjoxNjg4MjM3OTc0fQ.ys6C2KKCGq4xsUYNBluuTuxCjBQpchVoV_h0IbM9xEA

{
    "vote":"negative",
    "review":"Top Grade business"
}

### TESTING

GET http://localhost:3000/api/getUsers HTTP/1.1

### 

GET http://localhost:3000/api/admin/getBusiness HTTP/1.1

###
